openapi: 3.1.0
info:
  version: 1.0.0
  title: Products list
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: >
    Awesome products list
tags:
  - name: products
    description: pruducts API
servers:
  - url: http://localhost:3000
paths:
  # тут будуть посилання на ендпоінти
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
